### ISSUE TITLE
Item Pipes void their content on round robin mode

### ISSUE THREAD

**Issue by Madsoul01** [brachy84/GregTech#1]
**Describe the bug**
The pipe voids half of the items when transferring if the stack given is bigger than its capacity per second.Seems to only happen when the conveyor tranfers more items per second than the pipe can handle

**Versions**
GTCE: 1.16.1000

**Setup**
Playing Solo on test Flat world

**Steps To Reproduce**
1) Put Down three inventories and connect with item pipes and a conveyor on round robin
2) Put more items than the pipes throughput

**Expected behavior**
The pipe would distribute evenly all items

**Comment by brachy84** [comment]
This seems to happen also on isert first mode
